version: "3.8"
services:
        emuc_relay_db:
                container_name: emuc_relay_db
                image: mysql:5.7
                # MAC M1 사용시 platform설정
                platform: linux/amd64
                restart: always
#                environment:
#                        MYSQL_DATABASE: uplusbook_db
#                        MYSQL_USER: uplusbook
#                        MYSQL_PASSWORD: uplusbook!@#
#                        MYSQL_ROOT_PASSWORD: root
#                        TZ: Asia/Seoul
                env_file: env.db_local
                command:
                        - --character-set-server=utf8mb4
                        - --collation-server=utf8mb4_unicode_ci
                volumes:
                        - ./mysql/data:/var/lib/mysql:rw
#                        - ./mysql/conf:/etc/mysql:rw
#                        - ./mysql/init-files:/docker-entrypoint-initdb.d:ro
                ports:
                        - "33306:3306"
                expose:
                        - "3306"
#        emuc_alimtalk_db:
#                container_name: emuc_alimtalk_db
#                image: postgres:latest
#                # MAC M1 사용시 platform설정
#                platform: linux/amd64
#                restart: always
#                env_file: env.db_local
#                volumes:
#                        - ./postgresql/data:/var/lib/postgresql/data:rw
#                #                        - ./mysql/conf:/etc/mysql:rw
#                #                        - ./mysql/init-files:/docker-entrypoint-initdb.d:ro
#                ports:
#                        - "5432:5432"
#                expose:
#                        - "5432"
        eumc_oracle_db: # username : system, password : oracle
                platform: linux/amd64
                image: vitorfec/oracle-xe-18c
                environment:
                        - ORACLE_ROOT_PASSWORD=root
                        - ORACLE_PWD=ewhaadmin
                        - ORACLE_ALLOW_REMOTE=true
                ports:
                        - "5432:1521"
                volumes:
                        - ./oracle/data:/u01/app/oracle

#        eumc_backend_app:
#                build:
#                        context: .
#                        target: development
#                volumes:
#                        - .:/usr/src/app
#                      #  - /usr/src/app/node_modules
#                ports:
#                        - "4000:4000"
#                command: npm run start:dev
