import axios from '../axios';

const SUB_DIR = '/v1/insurance';

const getPaymentList = async (his_hsp_tp_cd, pt_no, fromdate, todate) =>
  await axios.get(`${SUB_DIR}/paymentList`, { params: { his_hsp_tp_cd, pt_no, fromdate, todate } });
// new Promise(resolve =>
//   resolve({
//     data: {
//       ok: true,
//       data: [
//         {
//           custom_out_card_rpy_amt: '28700',
//           custom_out_cash_rpy_amt: '0',
//           custom_out_meddept: 'FM',
//           custom_out_patsite: 'O',
//           custom_out_pre_amt: '0',
//           custom_out_rpy_pact_id: '1001717518',
//           custom_out_tot_ins: '17580',
//           custom_out_tot_insall: '0',
//           custom_out_tot_insown: '8790',
//           custom_out_tot_insreq: '8790',
//           custom_out_tot_rpy_amt: '28700',
//           custom_out_tot_spc: '0',
//           custom_out_tot_uin: '20000',
//           custom_out_tot_uni: '20000',
//           hsp_tp_cd: '01',
//           io_errmsg: '',
//           io_erryn: '',
//           out_acct_cursor: '',
//           out_acnt_no: '',
//           out_ampm: ' ',
//           out_aprv_tp_cd: 'Y',
//           out_bloodamt: '0',
//           out_card: '|9605010001|536148**********|삼성카드|68690426|일시불| ||',
//           out_card_rpy_amt: '28700',
//           out_cash: '|||||| ||',
//           out_cash_rpy_amt: '0',
//           out_citizen: '0221-96663-00124',
//           out_cmed_sum_amt: '0',
//           out_cmed_yn: '비지정',
//           out_con_inf: '',
//           out_custnm: ' ',
//           out_dcomn_cd: ' ',
//           out_deptname: '가정의학과',
//           out_dosno: '00000',
//           out_dosnostr: '',
//           out_drname: '이상화',
//           out_emepyn: '',
//           out_exdosno: '',
//           out_frvs_rmde_tp_cd: '재진',
//           out_grpamt: '0',
//           out_guide_cursor: '',
//           out_hipass_yn: 'N',
//           out_inpbdn_amt: '8700',
//           out_lastdate: '201902211445',
//           out_lsh_dtm: '2019-02-21 15:12',
//           out_med_dt_cursor: '',
//           out_med_rsv_tp_cd: '창구',
//           out_meddate: '2019-02-21 14:45',
//           out_mtcs_amt: '37580',
//           out_nins_sum_amt: '20000',
//           out_oncash_rpy_amt: '0',
//           out_pat_req_amt: '',
//           out_pathexam_yn: 'N',
//           out_pbdn_amt: '28700',
//           out_pme_cls_cd: '국민건강보험공단',
//           out_pse_cls_cd: '정상급여',
//           out_pt_nm: '김종형',
//           out_pv_rpy_amt: '0',
//           out_rcorg_grd_nm: '종 합 병 원',
//           out_rcpnm: '최지혁',
//           out_rdtn_amt: '0',
//           out_refundhp: '',
//           out_refundnm: '',
//           out_refundrlnm: '',
//           out_refundsignstr: '',
//           out_refundurl: '',
//           out_rpy_amt: '28700',
//           out_rpy_dt: '20190221',
//           out_rpy_stf_no: '96663',
//           out_rsvcnt: '',
//           out_spcpbdn_amt: '',
//           out_spcyn: 'Y',
//           out_uncl_amt: '0',
//           out_unn_brdn_amt: '8880',
//           out_vat_amt: '0',
//           out_w1_unit_cof_amt: '0',
//         },
//         {
//           custom_out_card_rpy_amt: '28700',
//           custom_out_cash_rpy_amt: '0',
//           custom_out_meddept: 'FM',
//           custom_out_patsite: 'O',
//           custom_out_pre_amt: '0',
//           custom_out_rpy_pact_id: '1001549339',
//           custom_out_tot_ins: '17580',
//           custom_out_tot_insall: '0',
//           custom_out_tot_insown: '8790',
//           custom_out_tot_insreq: '8790',
//           custom_out_tot_rpy_amt: '28700',
//           custom_out_tot_spc: '0',
//           custom_out_tot_uin: '20000',
//           custom_out_tot_uni: '20000',
//           hsp_tp_cd: '01',
//           io_errmsg: '',
//           io_erryn: '',
//           out_acct_cursor: '',
//           out_acnt_no: '',
//           out_ampm: ' ',
//           out_aprv_tp_cd: 'Y',
//           out_bloodamt: '0',
//           out_card: '|9605010001|536148**********|삼성카드|68690426|일시불| ||',
//           out_card_rpy_amt: '28700',
//           out_cash: '|||||| ||',
//           out_cash_rpy_amt: '0',
//           out_citizen: '0221-96663-00124',
//           out_cmed_sum_amt: '0',
//           out_cmed_yn: '비지정',
//           out_con_inf: '',
//           out_custnm: ' ',
//           out_dcomn_cd: ' ',
//           out_deptname: '가정의학과',
//           out_dosno: '00000',
//           out_dosnostr: '',
//           out_drname: '이상화',
//           out_emepyn: '',
//           out_exdosno: '',
//           out_frvs_rmde_tp_cd: '재진',
//           out_grpamt: '0',
//           out_guide_cursor: '',
//           out_hipass_yn: 'N',
//           out_inpbdn_amt: '8700',
//           out_lastdate: '201902211445',
//           out_lsh_dtm: '2019-02-21 15:12',
//           out_med_dt_cursor: '',
//           out_med_rsv_tp_cd: '창구',
//           out_meddate: '2019-02-21 14:45',
//           out_mtcs_amt: '37580',
//           out_nins_sum_amt: '20000',
//           out_oncash_rpy_amt: '0',
//           out_pat_req_amt: '',
//           out_pathexam_yn: 'N',
//           out_pbdn_amt: '28700',
//           out_pme_cls_cd: '국민건강보험공단',
//           out_pse_cls_cd: '정상급여',
//           out_pt_nm: '김종형',
//           out_pv_rpy_amt: '0',
//           out_rcorg_grd_nm: '종 합 병 원',
//           out_rcpnm: '최지혁',
//           out_rdtn_amt: '0',
//           out_refundhp: '',
//           out_refundnm: '',
//           out_refundrlnm: '',
//           out_refundsignstr: '',
//           out_refundurl: '',
//           out_rpy_amt: '28700',
//           out_rpy_dt: '20190221',
//           out_rpy_stf_no: '96663',
//           out_rsvcnt: '',
//           out_spcpbdn_amt: '',
//           out_spcyn: 'Y',
//           out_uncl_amt: '0',
//           out_unn_brdn_amt: '8880',
//           out_vat_amt: '0',
//           out_w1_unit_cof_amt: '0',
//         },
//         {
//           custom_out_card_rpy_amt: '28700',
//           custom_out_cash_rpy_amt: '0',
//           custom_out_meddept: 'FM',
//           custom_out_patsite: 'O',
//           custom_out_pre_amt: '0',
//           custom_out_rpy_pact_id: '1001549173',
//           custom_out_tot_ins: '17580',
//           custom_out_tot_insall: '0',
//           custom_out_tot_insown: '8790',
//           custom_out_tot_insreq: '8790',
//           custom_out_tot_rpy_amt: '28700',
//           custom_out_tot_spc: '0',
//           custom_out_tot_uin: '20000',
//           custom_out_tot_uni: '20000',
//           hsp_tp_cd: '01',
//           io_errmsg: '',
//           io_erryn: '',
//           out_acct_cursor: '',
//           out_acnt_no: '',
//           out_ampm: ' ',
//           out_aprv_tp_cd: 'Y',
//           out_bloodamt: '0',
//           out_card: '|9605010001|536148**********|삼성카드|68690426|일시불| ||',
//           out_card_rpy_amt: '28700',
//           out_cash: '|||||| ||',
//           out_cash_rpy_amt: '0',
//           out_citizen: '0221-96663-00124',
//           out_cmed_sum_amt: '0',
//           out_cmed_yn: '비지정',
//           out_con_inf: '',
//           out_custnm: ' ',
//           out_dcomn_cd: ' ',
//           out_deptname: '가정의학과',
//           out_dosno: '00000',
//           out_dosnostr: '',
//           out_drname: '이상화',
//           out_emepyn: '',
//           out_exdosno: '',
//           out_frvs_rmde_tp_cd: '재진',
//           out_grpamt: '0',
//           out_guide_cursor: '',
//           out_hipass_yn: 'N',
//           out_inpbdn_amt: '8700',
//           out_lastdate: '201902211445',
//           out_lsh_dtm: '2019-02-21 15:12',
//           out_med_dt_cursor: '',
//           out_med_rsv_tp_cd: '창구',
//           out_meddate: '2019-02-21 14:45',
//           out_mtcs_amt: '37580',
//           out_nins_sum_amt: '20000',
//           out_oncash_rpy_amt: '0',
//           out_pat_req_amt: '',
//           out_pathexam_yn: 'N',
//           out_pbdn_amt: '28700',
//           out_pme_cls_cd: '국민건강보험공단',
//           out_pse_cls_cd: '정상급여',
//           out_pt_nm: '김종형',
//           out_pv_rpy_amt: '0',
//           out_rcorg_grd_nm: '종 합 병 원',
//           out_rcpnm: '최지혁',
//           out_rdtn_amt: '0',
//           out_refundhp: '',
//           out_refundnm: '',
//           out_refundrlnm: '',
//           out_refundsignstr: '',
//           out_refundurl: '',
//           out_rpy_amt: '28700',
//           out_rpy_dt: '20190221',
//           out_rpy_stf_no: '96663',
//           out_rsvcnt: '',
//           out_spcpbdn_amt: '',
//           out_spcyn: 'Y',
//           out_uncl_amt: '0',
//           out_unn_brdn_amt: '8880',
//           out_vat_amt: '0',
//           out_w1_unit_cof_amt: '0',
//         },
//       ],
//     },
//   })
// );

export { getPaymentList };
